namespace Mostlylucid.Notify;

/// <summary>
///     Strongly-typed render contract. Implementations are source-generated by RazorSlices
///     (.cshtml -> RazorSlice&lt;TModel&gt; partial class) so there is no runtime Razor
///     and no reflection -- AOT-safe.
/// </summary>
/// <typeparam name="TModel">The model record consumed by the template.</typeparam>
public interface INotificationTemplate<in TModel>
{
    /// <summary>Subject line / push title / Slack-message-fallback string.</summary>
    string Subject(TModel model);

    /// <summary>HTML body for email; pre-rendered Slack blocks JSON for Slack; etc.</summary>
    Task<string> RenderHtmlAsync(TModel model, CancellationToken cancellationToken = default);

    /// <summary>Plain-text alternative. Email uses for multipart fallback; SMS uses directly.</summary>
    Task<string> RenderTextAsync(TModel model, CancellationToken cancellationToken = default);
}
